# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d8f7166ab574364391c5f16539d48b9d7bf0aebaba6697b624d74ff6cf015541dfed870fa5e15c4c337b00c81b76bbf948ee236278fac57068bac6d67e2b2bae

test:
  secret_key_base: 99ae533a46b520e72080dfaa1709c82ce0a36bed21049984117a9212e6e8e6567e999408d02d4497155ba8f44a86427af2e4321517eeccc54e809251d7aa0266

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
